apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: producer
  name: producer
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: producer
    spec:
      containers:
      - args:
        - python
        - producer.py
        - -p
        - "5672"
        - -s
        - rabbitmq.test-rabbitmq
        - -m
        - Hello
        - -r
        - "30"
        image: docker-registry.default.svc:5000/rabbitmq/producer
        imagePullPolicy: IfNotPresent
        name: producer
        resources: {}
      restartPolicy: Always
status: {}
